language: "perl"

perl:
  - "5.8"
  - "5.10"
  - "5.14"
  - "5.18"
  - "5.22"

env:
  matrix:
  - COVERALLS=true  DB=mysql
  global:
    secure: txA5GX+ymx+tM8VmVcpm38jMnOLn47ycmRgQxWZDFGBGk9e0g1PlDfIuyOt18wliLrNjV2InHy972FGJKlnGG1PwGAZctceUwjtrJhkqWfefAIvGiyyBUPVbJNV6C/D+1xNbD8LvObdLlNxH+ci/Ra1VAEHKKVLAywpU5JOh7eYKs+Jm1pqXZJvg0RiHqq/uULs+hYHNmmIlqRwBEHsHKyarTVHCCzbeiidzkkQuf7lQpJaDteO97r9P3npoBNijqDs3lQuSGblUzcjDuoAiQ5UhmxyU2yYU/x6lsVRETsKaVrvlJQJPXARAef5UE6mGDx4COcC6hz13wm7lHFrVSvThixNoxgslhcb8v9HmfGVIOxO5pHWnLTSNYUzEMp55SvavAyNdmqY6z9AXiDyOxruRGCkysUT8GwQTwMiXTn4/Qh8Tqe9kYbHXW4fEi7VQk8eo1HsQHdRw0xo8voBqoGVpPnk4E1FPs6OXTZbCQw61YqvJD8SO5wr+JaUl04FdRLOuP/iPwr1thFoDAhYU10Io2ztNlVgeeE1NJkLGpifY7fluQ+a0ddh3Tuq4y8tYXjesYBTGCSb+N7wGL/iV1w4mA7675F75B4o/Pau50QX5KxwU/+X02g6aOV2W0k9mFgbInaQu3VVfcRcN8lolbaHPeiAiwYjvDJatV181wiM=

sudo: required
dist: trusty
group: deprecated

addons:
  apt:
    packages:
      - unzip
      - mysql-server-5.6
      - apache2
      - libmysqlclient-dev
      - libpng12-dev
      - libssl-dev
      - openssl
      - mysql-client-5.6
      - mysql-client-core-5.6

before_install:
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
  - export CWD=$PWD
  - export DEPS=$HOME/dependencies
  - mkdir -p $DEPS
  - cd $DEPS
  - $CWD/travisci/get_dependencies.sh
  - cd $CWD

install:
  - export CWD=$PWD
  - export DEPS=$HOME/dependencies
  - export KENT_SRC="$DEPS/kent-335_base/src"
  - export HTSLIB_DIR="$DEPS/htslib"
  - export MACHTYPE=$(uname -m)
  - export CFLAGS="-fPIC"
  - export PERL5LIB=$DEPS/bioperl-live-release-1-6-924:$PERL5LIB
  - cd $DEPS
  - $CWD/travisci/build_c.sh
  - cd $CWD
  - cpanm --quiet --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
  - cpanm --quiet --installdeps --with-recommends --notest .
  - cpanm --quiet -n Devel::Cover::Report::Coveralls
  - cp travisci/MultiTestDB.conf.travisci  t/MultiTestDB.conf

script: "./travisci/harness.sh"

jobs:
  include:
    - stage: trigger_dependent_builds
      script: ./travisci/trigger-dependent-build.sh

notifications:
  email:
    on_success: always
    on_failure: always
