language: "perl"

perl:
  - "5.8.8"
  - "5.10"
  - "5.14"
  - "5.22"

env:
  - COVERALLS=true  DB=mysql

sudo: false

addons:
    apt:
        packages:
        - unzip

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - wget https://github.com/bioperl/bioperl-live/archive/release-1-6-924.zip
    - unzip release-1-6-924.zip
    - git clone --branch master --depth 1 https://github.com/samtools/htslib.git
    - cd htslib
    - make
    - cd ..


install:
    - cpanm --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - cpanm --installdeps --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - export HTSLIB_DIR=$PWD/htslib
    - export PERL5LIB=$PWD/bioperl-live-release-1-6-924
    - cpanm Bio::DB::HTS
    - cp travisci/MultiTestDB.conf.travisci  t/MultiTestDB.conf

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
